services:
  - type: background-worker
    name: stock-telegram-bot
    env: python
    buildCommand: ./build.sh
    startCommand: python Main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
